name: BuildApk
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease
      - name: List Build Tools Files
        run: ls /usr/local/lib/android/sdk/build-tools/
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - run: mv ${{steps.sign_app.outputs.signedReleaseFile}} MIWU_$GITHUB_REF_NAME.apk
      - name: Archive Apk File
        uses: actions/upload-artifact@v3
        with:
          name: apk_file
          path: app/build/outputs/apk/release
